
from models.venue import VenueModel
from models.venue_comments import VenueCommentModel
from models.types import TypeModel

venue_type_list = [
    TypeModel(type="Outdoor"),
    TypeModel(type="Indoor"),
    ]

venue_list = [
    VenueModel(
        email="Windmill@Windmill.com",
        username="Bobby", 
        password="Windmill1",
        profileImage = "https://res.cloudinary.com/tjmcodes/image/upload/v1656844656/my_found_sounds_pics/r673ncsqnjycl9pztuze.jpg",
        title="Bob Smith",
        role="Manager",
        venueName="The Windmill",
        type = venue_type_list,
        # venueImage="https://upload.wikimedia.org/wikipedia/commons/6/6a/Windmill%2C_Brixton_Hill%2C_SW2_%283151353450%29.jpg",
        location="london",
        address="22 Blenheim Gardens, Brixton Hill, London SW2 5BZ", 
        budget=100, 
        websiteUrl="https://www.windmillbrixton.co.uk/", 
        # videoUrl="", 
        # optionUrl="", 
        backgroundCardImage="https://i0.wp.com/www.brixtonbuzz.com/wp-content/uploads/2012/02/windmill-brixton-1.jpg?resize=640%2C433",
        galleryImage1="https://i0.wp.com/www.brixtonbuzz.com/wp-content/uploads/2012/02/windmill-brixton-1.jpg?resize=640%2C433", 
        galleryImage2="", 
        galleryImage3="", 
        description="If there was ever a venue that proved true the old maxim, never judge a book by its cover, The Windmill is it. Though this little back-street pub couldn’t look more unassuming if it tried, its reputation as a champion of great music, and a great place to catch a live gig stretches far and wide. The Windmill has been a lot of things in its lifetime, but morphed into a music venue in the early 2000s simply by chance, when somebody realised that its regular crowd possessed a wealth of skills in areas such as sound engineering, promotion, and music production. Sinche bar has been named as one of the best live music venues not only in London but in the country",
        fbUrl="https://en-gb.facebook.com/windmillbrixton/", 
        twitterUrl="https://twitter.com/WindmillBrixton", 
        youTubeUrl="https://www.youtube.com/watch?v=qpegm3h79y0",
        instagramUrl="https://www.instagram.com/windmillbrixton/?hl=en"),

    VenueModel(
        email="dublincastle@dublincastle.com",
        username="Patrick", 
        password="Dublincastle1",
        profileImage = "https://res.cloudinary.com/dgk61wxpy/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1659801516/139912860-close-up-headshot-portrait-of-smiling-mature-man-sit-on-couch-at-home-look-at-camera-posing-happy-se_pzpdb7.jpg",
        title="Micheal Higgins",
        role="owner",
        venueName="The Dublin Castle",
        type = venue_type_list,
        # venueImage="https://s3.amazonaws.com/sndb/uploads/photo/image/418883/large_image.jpg",
        location="london",
        address="94 Parkway, London NW1 7AN", 
        budget=400, 
        websiteUrl="https://thedublincastle.com/", 
        # videoUrl="https://www.youtube.com/watch?v=hVI9YoYLQ7k", 
        # optionUrl="", 
        backgroundCardImage="https://cdn.londonandpartners.com/asset/d695548057eb86760476f239b35fc8f5.jpg",
        galleryImage1="https://cdn.londonandpartners.com/asset/d695548057eb86760476f239b35fc8f5.jpg", 
        galleryImage2="", 
        galleryImage3="", 
        description="A favourite of the late Amy Winehouse, who could often be caught serving pints behind the bar, Dublin Castle has courted an outstanding reputation as a live music venue since the 1970s, when the band Madness secured a residency there — though they had to pretend to be a blues band just to get their first gig, having been turned down previously. The pub, which was a mainstay of the 90s Britpop movement, has been run by the same family for nearly 30 years, and is a self proclaimed ‘indie rock institution’, rather than just another music venue.",
        fbUrl="https://en-gb.facebook.com/groups/thedublincastle/",
        twitterUrl="https://twitter.com/thedublincastle", 
        youTubeUrl="https://www.youtube.com/thedublincastletv",
        instagramUrl="https://www.youtube.com/thedublincastletv"),

        VenueModel(
        email="YES@YES.com",
        username="YES", 
        password="YES1!YES",
        profileImage = "https://res.cloudinary.com/dgk61wxpy/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1659802002/Findartistsandvenues-profile-images/portrait-of-young-female-bar-owner-picture-id1084751504_dmmlrg.jpg",
        title="Ben Tan",
        role="Assistant Manager",
        venueName="YES",
        type = venue_type_list,
        location="manchester",
        address="38 Charles Street, M1 7DB.", 
        budget=100, 
        websiteUrl="https://www.yes-manchester.com/", 
        backgroundCardImage="https://mn2s-content.s3.eu-west-2.amazonaws.com/wp-content/uploads/2018/10/13143919/manchester_nightlife_yes-1024x488.png",
        galleryImage1="https://images.squarespace-cdn.com/content/v1/5b0dd7581aef1d319395b854/1561984746521-R6UQ64JA35V4LMS29S6Y/Shame+-+The+Pink+Room+YES+-+26-06-19-32.jpg?format=1000w", 
        galleryImage3="https://s3-eu-west-1.amazonaws.com/gitpics/wp-content/uploads/2020/01/23220048/Black_Country_New_Road_YES_Rachel_Bywater_03.jpg", 
        galleryImage2="https://giglist.com/storage/app/uploads/public/5e8/e2e/be6/5e8e2ebe6fedd779608726.jpg", 
        description="One of the most popular live music venues in the city, YES is ideally situated near the student district of Manchester, with a calendar packed full of gigs for the entire summer. There’s a whole array of genres in store, too, including rock n roll, live DJs and even an ABBA event – with a casual bar downstairs serving pizza from Pepperoni Playboy and vegan doner kebabs from Doner Summer",
        fbUrl="https://www.facebook.com/yesmanchester/", 
        twitterUrl="https://twitter.com/yes_mcr/", 
        youTubeUrl="tba",
        instagramUrl="https://www.instagram.com/yes_mcr/"),

        VenueModel(
        email="jamboree@jamboree.com.",
        username="jamboree1", 
        password="jamboree1!",
        profileImage = "https://res.cloudinary.com/dgk61wxpy/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1659802002/Findartistsandvenues-profile-images/portrait-of-young-female-bar-owner-picture-id1084751504_dmmlrg.jpg",
        title="Jane Bedford",
        role=" Manager",
        venueName="The Jamboree",
        type = venue_type_list,
        # venueImage="https://images.cm.archant.co.uk/resource/image/3587104/landscape_ratio16x9/448/252/47ba54364c585125d57c68751e5f2827/uH/el-10-jamboree-campaign-5-cabl.jpg",
        location="london",
        address="6 St Chads Place,London, WC1X 9HH", 
        budget=400, 
        websiteUrl="https://www.jamboreevenue.co.uk/", 
        # videoUrl="", 
        # optionUrl="", 
        backgroundCardImage="https://www.jamboreevenue.co.uk/wp-content/uploads/2011/05/jamboree.jpg",
        galleryImage1="https://www.jamboreevenue.co.uk/wp-content/uploads/2011/05/jamboree.jpg", 
        galleryImage2="https://images.cm.archant.co.uk/resource/blob/3587096/e1c96eaf4761d98d509063bab2fc3386/el-10-jamboree-campaign-1-cabl-data.jpg", 
        galleryImage3="https://i0.wp.com/www.eastlondonlines.co.uk/ell_wp/wp-content/uploads/2018/03/interior.jpg?resize=750%2C422", 
        description="Peel black the velvet curtain and step-inside a home-made den of world music with devil may care European bohemia, crackled walls and mismatched furniture, raucous evenings, a rag-tag of eccentric characters, flowing absinthe and mad dancing. Order local ale from the charmingly peculiar bar man, possibly wearing a ripped ladies' pinafore with a string of Pat Butcher pearls … and pull up a seat to watch the Mad Hatter's tea party begin.",
        fbUrl="https://www.facebook.com/jamboreelimehouse", 
        twitterUrl="https://twitter.com/jamboreevenue", 
        youTubeUrl="https://www.youtube.com/user/jamboreevenue",
        instagramUrl=""),

        VenueModel(
        email="nightandday@nightandday.com.",
        username="nightandday", 
        password="nightandday1!",
        profileImage = "https://res.cloudinary.com/dgk61wxpy/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1659802002/Findartistsandvenues-profile-images/portrait-of-young-female-bar-owner-picture-id1084751504_dmmlrg.jpg",
        title="Cornelia Jacobs",
        role=" Assistant Manager",
        venueName="Night and Day Cafe",
        type = venue_type_list,
        location="manchester",
        address="26 Oldham Street Manchester M1 1JN", 
        budget=100, 
        websiteUrl="https://nightnday.org/", 
        backgroundCardImage="https://nightnday.org/wp-content/uploads/2020/02/Beeswaxx_220220_GaryBrown-12-1024x682.jpg",
        galleryImage1="https://nightnday.org/wp-content/uploads/2019/11/TAF_0858-1024x683.jpg", 
        galleryImage2="https://nightnday.org/wp-content/uploads/2019/11/TAF_0410-1-1024x683.jpg", 
        galleryImage3="https://nightnday.org/wp-content/uploads/2020/02/Beeswaxx_220220_GaryBrown-63-1024x682.jpg", 
        description="The Night & Day opened in 1991 as a chip shop in what was (at the time) one of the rougher parts of town. Owned by Jan Oldenburg, it slowly developed into a music venue and gained a reputation for pioneering live music and supporting alternative bands. When the venue faced the threat of closure Elbow’s Guy Garvey told radio station XFM that the venue had been crucial to his band's career and that it deserved protected status and a blue plaque.",
        fbUrl="https://www.facebook.com/jamboreelimehoue", 
        twitterUrl="https://twitter.com/jamboreevene", 
        youTubeUrl="https://www.youtube.com/user/jambreevenue",
        instagramUrl=""),

        VenueModel(
        email="thewardrobe@thewardrobe.com.",
        username="thewardrobe", 
        password="thewardrobe1!",
        profileImage = "https://res.cloudinary.com/dgk61wxpy/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1659802002/Findartistsandvenues-profile-images/portrait-of-young-female-bar-owner-picture-id1084751504_dmmlrg.jpg",
        title="Lea sirk",
        role="Entertainment Manager",
        venueName="The Wardrobe",
        type = venue_type_list,
        location="leeds",
        address="6 St Peter’s Square, Quarry Hill, Leeds, West Yorkshire, LS9 8AH", 
        budget=100, 
        websiteUrl="https://www.thewardrobe.co.uk/", 
        backgroundCardImage="https://images.squarespace-cdn.com/content/v1/606c6ebf76f0695e44cb1c15/28dead18-28f2-431b-95c4-eec9aef4f4a1/LAL_THESHERLOCKS_%40APERTUNES-46.jpg?format=2500w",
        galleryImage1="https://i2-prod.leeds-live.co.uk/incoming/article16652803.ece/ALTERNATES/s1200c/0_Wardrobejpeg.jpg", 
        galleryImage3="https://licklist.s3-eu-west-2.amazonaws.com/images/original/000/000/073/123/137-l7fkqxr8pi8tnaer.jpg", 
        galleryImage2="https://blog.seetickets.com/wp-content/uploads/ghostpoet.jpeg", 
        description="If you want to check out the best new bands on their way to the big time, take a look at The Wardrobe’s listings. This 450-capacity underground bolthole sits beneath a cool, music-loving bar and has been putting on must-see gigs for over two decades. Amy Whitehouse, First Aid Kit and Catfish and the Bottlemen are just a few who have passed through these doors before reaching stardom – with over 250 gigs and club nights a year, there’s always something to see.",
        fbUrl="https://www.facebook.com/thewardrobeleeds/", 
        twitterUrl="https://twitter.com/wardrobeleeds", 
        youTubeUrl="tba",
        instagramUrl="https://www.instagram.com/p/Cc7rp_Ht2TU/"),

        VenueModel(
        email="thenightowl@thenightowl.com",
        username="thenightowl", 
        password="Thenightowl1!",
        profileImage = "https://res.cloudinary.com/dgk61wxpy/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1659802002/Findartistsandvenues-profile-images/portrait-of-young-female-bar-owner-picture-id1084751504_dmmlrg.jpg",
        title="Cyprian Zeni",
        role="Manager",
        venueName="The Night Owl",
        type = venue_type_list,
        location="Birmingham",
        address="17-18 Lower Trinity Street, Digbeth, Birmingham, B9 4AG", 
        budget=100, 
        websiteUrl="https://birmingham.thenightowl.club/", 
        backgroundCardImage="https://birmingham.thenightowl.club/wp-content/uploads/sites/5/2021/05/The-Bongolian-29.jpg",
        galleryImage1="https://media.timeout.com/images/105861615/750/422/image.jpg", 
        galleryImage3="https://eu-assets.simpleview-europe.com/birmingham-visit/imageresizer/?image=%2Fdmsimgs%2F54462986855C6057E0EE9EA5005DFFDD0AE001B4.jpg&action=ProductDetailProFullWidth", 
        galleryImage2="https://theculturetrip.com/wp-content/uploads/2017/02/the-night-owl-jonathan-morgan.jpg", 
        description="Visiting The Night Owl is like stepping back in time. It calls itself the ‘Midlands’ only Northern Soul and Motown bar’ and has a quirky, vintage interior. It even has a camera on the DJ booth that projects the label of the vinyl record being played onto the club wall. An evening here certainly makes for one eventful night.The venue even has a sprung wooden dance floor especially for energetic Northern soul dancing. So whether you’re attending a dance class, live band performance or DJ night, the sheer theatrics of the records, clothes and dancing will have you realising why fans of Northern Soul believe that it’s more than just a type of music – it’s a way of life.",
        fbUrl="https://www.facebook.com/thenightowlbham", 
        twitterUrl="https://twitter.com/thenightowlbham", 
        youTubeUrl="https://www.youtube.com/channel/UCYaGu8IFkM_yiTs80JXsdxQ",
        instagramUrl="https://instagram.com/thenightowlbirmingham/"),


        VenueModel(
        email="Thejacaranda@thejacaranda.com",
        username="Thejacaranda", 
        password="Thejacaranda1!",
        profileImage = "https://res.cloudinary.com/dgk61wxpy/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1659802002/Findartistsandvenues-profile-images/portrait-of-young-female-bar-owner-picture-id1084751504_dmmlrg.jpg",
        title="Vincent Bueno",
        role="Entertainment Manager",
        venueName="The Jacaranda & Phase One",
        type = venue_type_list,
        location="Liverpool",
        address="21-23 Slater Street & 40 Seel Street", 
        budget=100, 
        websiteUrl="https://www.jacarandarecords.com/phaseone/", 
        backgroundCardImage="https://signaturesliverpool.co.uk/wp-content/uploads/2018/10/Jac.jpg",
        galleryImage1="https://independent-liverpool.co.uk/wp-content/uploads/2019/02/bokante-1024x683.jpg", 
        galleryImage3="https://s3-eu-west-1.amazonaws.com/gitpics/wp-content/uploads/2018/07/23170640/Jacaranda-Phase-One-25.jpg", 
        galleryImage2="https://s3-eu-west-1.amazonaws.com/gitpics/wp-content/uploads/2018/07/23165722/Jacaranda-Phase-One-7.jpg", 
        description="Renowned as being the first club to host The Beatles in 1960, The Jacaranda is a staple of the Liverpool music scene. First opening in the late 1950s as a coffee bar, this legendary music venue is steeped in fascinating musical heritage. After a mysterious closure in 2011 amidst a changing Liverpool nightlife landscape, many wondered if there was a future for the iconic club. However, to the delight of music lovers, it reopened a few years later as a record store, coffee shop, bar and live music venue. Since then, the venue has hosted a number of rock n’ roll artists and indie performers. In the last year or so, The Jacaranda have expanded the brand and opened a brand-new venue in the heart of Liverpool, Jacaranda Phase One. This urban and edgy space boasts a large courtyard, a record store area and unique live music Liverpool set up.",
        fbUrl="https://www.facebook.com/JacRecordsLtd/", 
        twitterUrl="https://twitter.com/JacRecordsLtd", 
        youTubeUrl="https://www.youtube.com/channel/UCWYikOs5NF1CbpKRwD-E08g",
        instagramUrl="https://www.instagram.com/jacrecordsltd/"),

        VenueModel(
        email="theoldbluelast@theoldbluelast.com",
        username="theoldbluelast", 
        password="Theoldbluelast1!",
        profileImage = "https://res.cloudinary.com/dgk61wxpy/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1659802002/Findartistsandvenues-profile-images/portrait-of-young-female-bar-owner-picture-id1084751504_dmmlrg.jpg",
        title="sam walker",
        role="Manager",
        venueName="The Old Blue Last",
        type = venue_type_list,
        location="London",
        address="he Old Blue Last 38 Great Eastern St Shoreditch EC2A 3ES", 
        budget=100, 
        websiteUrl="https://www.theoldbluelast.com/", 
        backgroundCardImage="https://hotvox.co.uk/wp-content/uploads/OBL-Gallery-3.jpg",
        galleryImage1="https://i2-prod.mylondon.news/incoming/article23799555.ece/ALTERNATES/s615/2_gettyimages-469438777-594x594.jpg", 
        galleryImage3="https://assets.londonist.com/uploads/2016/07/i730/the_old_blue_last.jpg", 
        galleryImage2="https://fms-mag.com/wp-content/uploads/2016/07/Spector_1476.jpg", 
        description="To be considered the ‘best live music venue in London’ is quite an achievement, especially for a space of this size. A quirky mix of legendary acts have graced this stage (check out the list on their site if you have a spare minute or ten), but history was made here long before performances at The Old Blue Last.Once a former brothel, it was also known as a hang-out spot of Shakespeare himself. Does that make this the coolest venue venue in London? Either way, we should respect it, it is hundreds of years old after all.",
        fbUrl="tba", 
        twitterUrl="tba", 
        youTubeUrl="tba",
        instagramUrl="tba"),

        VenueModel(
        email="mattandphreds@mattandphreds.com/",
        username="mattandphreds", 
        password="Mattandphreds1!",
        profileImage = "https://res.cloudinary.com/dgk61wxpy/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1659802002/Findartistsandvenues-profile-images/portrait-of-young-female-bar-owner-picture-id1084751504_dmmlrg.jpg",
        title="matt Phred",
        role="Founder",
        venueName="Matt and Phreds",
        type = venue_type_list,
        location="Manchester",
        address="64 Tib St Manchester M4 1EB", 
        budget=100, 
        websiteUrl="https://mattandphreds.com/", 
        backgroundCardImage="https://www.creativetourist.com/app/uploads/2013/11/matt-and-phreds-sign-manchester-music.jpeg",
        galleryImage1="https://static.designmynight.com/uploads/2019/06/Matt-and-Phreds-1-optimised.jpg", 
        galleryImage3="https://media-cdn.tripadvisor.com/media/photo-s/04/a7/8b/ec/matt-and-phred-s-jazz.jpg", 
        galleryImage2="https://bloke2018.files.wordpress.com/2018/04/img_20180418_2234083621352145066475092.jpg", 
        description="Once upon a time, in a year nobody can agree on, two musicians named Matt & Phred decided to open a Jazz Club. In 2010, some years after both musicians had left for pastures new, the Turner family took over the little back street Jazz Club and have been enjoying meeting musicians and guests from all over the world ever since. The club has now firmly established itself as one of Manchester city-centre’s most dearly loved live music venues, with an emphasis on creating an atmosphere people from different backgrounds and ages can all enjoy as one. There’s been more than one night our favourite octogenarian has danced the night away amazing the younger crowd with her high flying kicks and splits!",
        fbUrl="http://facebook.com/mattandphreds", 
        twitterUrl="http://twitter.com/mattandphreds", 
        youTubeUrl="http://youtube.com/mattandphreds",
        instagramUrl="http://instagram.com/mattandphreds"),

        VenueModel(
        email="BrudenellSocialClub@BrudenellSocialClub.com",
        username="BrudenellSocialClub", 
        password="BrudenellSocialClub1!",
        profileImage = "https://res.cloudinary.com/dgk61wxpy/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1659802002/Findartistsandvenues-profile-images/portrait-of-young-female-bar-owner-picture-id1084751504_dmmlrg.jpg",
        title="Bryoni miller",
        role="Performace co-ordinator",
        venueName="Brudenell Social Club",
        type = venue_type_list,
        location="leeds",
        address="33 Queen’s Road, Leeds, West Yorkshire, LS6 1NY.", 
        budget=100, 
        websiteUrl="http://www.brudenellsocialclub.co.uk/", 
        backgroundCardImage="http://synthbucket.s3-eu-west-1.amazonaws.com/wp-content/uploads/2020/02/25103428/24Feb_AllTimeLow_Leeds_GlenB-16.jpg",
        galleryImage1="https://images.squarespace-cdn.com/content/v1/5b0dd7581aef1d319395b854/1537821011116-OQWVFKGIYU2X36BSSIRI/Fizzy+Blood+-+Brudenell+Social+Club+-+19-9-18+-+Leeds-71.jpg?format=1000w", 
        galleryImage3="http://www.nationalrockreview.com/wp-content/gallery/thetubes-brudenellsocialclub-leeds_uk-20150811-adamkennedy/thetubes-brudenellsocialclub-leeds_uk-20150811-adamkennedy-04.jpg", 
        galleryImage2="https://counterfeitmag.co.uk/wp-content/uploads/2016/05/She-Makes-War-1.jpg", 
        description="Think of live music in Leeds and the Brudenell is likely the first place to come to mind. It’s one of the most important music venues in the country. This pub-cum-venue has three different gig rooms, the largest for up to 400 people. Shows happen nearly every night of the week as up and coming artists make their mark, but its reputation also means they welcome stars – Sam Fender, Johnny Marr and Tom Jones have all graced its hallowed stage in recent years",
        fbUrl="tba", 
        twitterUrl="tba", 
        youTubeUrl="tba",
        instagramUrl="tba"),

        VenueModel(
        email="Headrow House",
        username="HeadrowHouse", 
        password="HeadrowHouse1!",
        profileImage = "https://res.cloudinary.com/dgk61wxpy/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1659802002/Findartistsandvenues-profile-images/portrait-of-young-female-bar-owner-picture-id1084751504_dmmlrg.jpg",
        title="Elina Noella",
        role="Organizer",
        venueName="Headrow House",
        type = venue_type_list,
        location="leeds",
        address="Bramley’s Yard, 19 The Headrow, Leeds. West Yorkshire, LS1 6PU.", 
        budget=100, 
        websiteUrl="https://headrowhouse.com/", 
        backgroundCardImage="https://louderthanwar.com/wp-content/uploads/2015/11/Ex_Hex-22.jpg",
        galleryImage1="https://thumbs.dreamstime.com/b/nick-j-d-hodgson-headrow-house-leeds-110681301.jpg", 
        galleryImage3="https://static.ra.co/images/news/2021/natural-selection-leeds2.jpeg", 
        galleryImage2="https://i2-prod.examinerlive.co.uk/incoming/article11416745.ece/ALTERNATES/s1200b/JS91560711.jpg", 
        description="For modern tunes and underground sounds, Headrow House invites you up to their first floor gig space – it sits above their huge beer hall and hosts just 150 people, which makes it one of the best intimate music venues in Leeds. They’re on the pulse, so expect the next generation of cutting edge talent to take to their stage, alongside special shows from big names – it’s seen the likes of Loyle Carner, Biffy Clyro and Everything Everything play since it opened in 2015.",
        fbUrl="tba", 
        twitterUrl="tba", 
        youTubeUrl="tba",
        instagramUrl="tba"),

        VenueModel(
        email="TheCavern@TheCavern",
        username="TheCavern", 
        password="TheCavern1!",
        profileImage = "https://res.cloudinary.com/dgk61wxpy/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1659802002/Findartistsandvenues-profile-images/portrait-of-young-female-bar-owner-picture-id1084751504_dmmlrg.jpg",
        title="Donna Moss",
        role="Manager",
        venueName="The Cavern",
        type = venue_type_list,
        location="liverpool",
        address="10 McCartney St, Liverpool L2 6RE", 
        budget=100, 
        websiteUrl="https://www.cavernclub.com/whats-on/", 
        backgroundCardImage="https://cdn.mos.cms.futurecdn.net/sEQ6wcUqUa4GVH4hqxM3FZ.jpg",
        galleryImage1="https://scdn.aro.ie/Sites/50/titanichotelliverpool2018/uploads/images/PanelImages/General/The_Cavern_of_the_Cavern_Club_clip,_2009_1.jpg", 
        galleryImage3="https://eu-assets.simpleview-europe.com/marketingliverpool/imageresizer/?image=%2Fdmsimgs%2FCavern_Club_2_1456274396.png&action=ProductDetail", 
        galleryImage2="https://i2-prod.mirror.co.uk/incoming/article10504541.ece/ALTERNATES/s615b/PROD-The-Cavern-Club-the-world-famous-nightclub-on-Mathew-Street-in-Liverpool-which-was-the-birthplace.jpg", 
        description="The Cavern has proudly stood on Mathew Street for seven decades and is the cradle of British pop culture in Liverpool. From The Beatles’ first performance in February 1961 to the Arctic Monkeys pre-breakthrough gig in October 2005, the Cavern remains the beating heart of Liverpool’s amazing music scene. The iconic stage beneath the brick arches is the image most people associate with the Cavern. This is where you can enjoy live music from soloists and cover bands from mid-afternoon until late evening. Open 7 days a week, you’ll experience everything from Rock n Roll to solo acoustic, as well as Cavern Club resident artists and top-class Merseybeat tribute acts",
        fbUrl="tba", 
        twitterUrl="tba", 
        youTubeUrl="tba",
        instagramUrl="tba"),

        VenueModel(
        email="MothClub@mothclub.com",
        username="Mothclud", 
        password="Mothclub1!",
        profileImage = "https://res.cloudinary.com/dgk61wxpy/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1659802002/Findartistsandvenues-profile-images/portrait-of-young-female-bar-owner-picture-id1084751504_dmmlrg.jpg",
        title="Dana Ronde",
        role="Manager",
        venueName="The Moth Club",
        type = venue_type_list,
        location="London",
        address="Old Trades Hall, Valette St, London E9 6NU", 
        budget=100, 
        websiteUrl="https://mothclub.co.uk/", 
        backgroundCardImage="https://offloadmedia.feverup.com/secretldn.com/wp-content/uploads/2018/09/18121124/moth1.jpg",
        galleryImage1="https://www.crowdfunder.co.uk/uploads/project_images/1c/c9/855517/1587830565_84399683_1870354963271266_7938656080630906880_o.jpg", 
        galleryImage3="https://www.crowdfunder.co.uk/uploads/projects/855517.jpg?1587828976", 
        galleryImage2="https://offloadmedia.feverup.com/secretldn.com/wp-content/uploads/2018/09/18121121/moth2-666x445.jpg", 
        description="All that glitters is gold in this venue. Their eclectic programming is one of MOTH Club’s strengths. Gigs and concerts from up-and-coming bands are always on the bill at very reasonable prices, frequently selling out. For the avid gig-goer, this venue is great for the more intimate experience, with the stage well within spitting distance of the crowd. The stage is hallowed ground, and has been graced by likes of artists from Connan Mockasin to Lady Gaga.",
        fbUrl="tba", 
        twitterUrl="tba", 
        youTubeUrl="tba",
        instagramUrl="tba"),


        VenueModel(
        email="jamhouse@jam.com",
        username="thejamhouse", 
        password="TheJamHouse1!",
        profileImage = "https://res.cloudinary.com/dgk61wxpy/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1659802002/Findartistsandvenues-profile-images/portrait-of-young-female-bar-owner-picture-id1084751504_dmmlrg.jpg",
        title="John Lundvik",
        role="Entertainment manager",
        venueName="The Jam House",
        type = venue_type_list,
        location="Birmingham",
        address="The Jam House, 3-5 St Pauls Square, Birmingham B3 1QU", 
        budget=100, 
        websiteUrl="https://thejamhouse.com/", 
        backgroundCardImage="https://eu-assets.simpleview-europe.com/birmingham-visit/imageresizer/?image=%2Fdmsimgs%2Fevent-130_1980_website_1757254899.jpg&action=ProductDetailProFullWidth",
        galleryImage1="https://img.tagvenue.com/upload/4d/ae/19003-stage-area-room.jpg", 
        galleryImage3="https://thejamhouse.com/wp-content/uploads/2019/11/latinmotion-dance-scene.jpg", 
        galleryImage2="https://www.bbc.co.uk/staticarchive/9a010e41d0cb0a11c6a2e109d87ac6cb063adf96.jpg", 
        description="The Jam House is a great venue that seeks to combine delicious food and excellent drinks with outstanding live music. The Jam House focuses mostly on jazz and blues artists who entertain guests throughout the night. However, besides upcoming jazz acts, such as Jazzlines or Jocelyn Brown, the Jam House’s event calendar includes other special music events, like an evening dedicated to live salsa music, which invites guests to dance the night away. The venue also has an amazing balcony, right above the main stage, where guests can enjoy performances in a great atmosphere.",
        fbUrl="tba", 
        twitterUrl="tba", 
        youTubeUrl="tba",
        instagramUrl="tba"),


        VenueModel(
        email="bluearrow@thebluearrow.com",
        username="thebluearrow", 
        password="TheBlueArrow1!",
        profileImage = "https://res.cloudinary.com/dgk61wxpy/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1659802002/Findartistsandvenues-profile-images/portrait-of-young-female-bar-owner-picture-id1084751504_dmmlrg.jpg",
        title="Bryan murphy",
        role="Manager",
        venueName="The Blue Arrow",
        type = venue_type_list,
        location="glasgow",
        address="323 Sauchiehall St, Glasgow G2 3HW", 
        budget=100, 
        websiteUrl="https://www.bluearrowjazzclub.com/", 
        backgroundCardImage="https://static.designmynight.com/uploads/2019/10/The-Blue-Arrow2-620x330-optimised.jpg",
        galleryImage1="https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/fa/8a/13/late-night.jpg?w=1200&h=1200&s=1", 
        galleryImage3="https://i2-prod.glasgowlive.co.uk/incoming/article14286047.ece/ALTERNATES/s1200b/1_Club-Purple_previewjpeg.jpg", 
        galleryImage2="https://myplayer.ams3.cdn.digitaloceanspaces.com/21970/conversions/cMBeiheac6MMpzqNLFlm0aWSpgaixl-metaU2NyZWVuc2hvdCAyMDIxLTAzLTIyIGF0IDEwLjMwLjMwLnBuZw%3D%3D--thumb.jpg", 
        description="Since opening in February 2018, The Blue Arrow has tapped into the local music scene and created plenty of buzz around the city’s ‘new home of jazz’. It doesn’t get much more atmospheric than this cosy basement bar, which comes complete with cabaret tables, red theatre lights and exposed bricks Award-winning local talents such as Fergus McCreadie and David Bowden can share a stage with touring artists including Jannette Mason and other established names. Embracing the new generation of performers, as well as honouring and referencing the Jazz greats, the past and present collide in this intimate basement bar. Order a drink, sit back and enjoy the music",
        fbUrl="tba", 
        twitterUrl="tba", 
        youTubeUrl="tba",
        instagramUrl="tba"),


        # VenueModel(
        # email="",
        # username="", 
        # password="",
        # profileImage = "https://res.cloudinary.com/dgk61wxpy/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1659802002/Findartistsandvenues-profile-images/portrait-of-young-female-bar-owner-picture-id1084751504_dmmlrg.jpg",
        # title="",
        # role="",
        # venueName="",
        # type = venue_type_list,
        # location="",
        # address="", 
        # budget=100, 
        # websiteUrl="", 
        # backgroundCardImage="",
        # galleryImage1="", 
        # galleryImage3="", 
        # galleryImage2="", 
        # description="",
        # fbUrl="tba", 
        # twitterUrl="tba", 
        # youTubeUrl="tba",
        # instagramUrl="tba"),


        # VenueModel(
        # email="",
        # username="", 
        # password="",
        # profileImage = "https://res.cloudinary.com/dgk61wxpy/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1659802002/Findartistsandvenues-profile-images/portrait-of-young-female-bar-owner-picture-id1084751504_dmmlrg.jpg",
        # title="",
        # role="",
        # venueName="",
        # type = venue_type_list,
        # location="",
        # address="", 
        # budget=100, 
        # websiteUrl="", 
        # backgroundCardImage="",
        # galleryImage1="", 
        # galleryImage3="", 
        # galleryImage2="", 
        # description="",
        # fbUrl="tba", 
        # twitterUrl="tba", 
        # youTubeUrl="tba",
        # instagramUrl="tba"),


        # VenueModel(
        # email="",
        # username="", 
        # password="",
        # profileImage = "https://res.cloudinary.com/dgk61wxpy/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1659802002/Findartistsandvenues-profile-images/portrait-of-young-female-bar-owner-picture-id1084751504_dmmlrg.jpg",
        # title="",
        # role="",
        # venueName="",
        # type = venue_type_list,
        # location="",
        # address="", 
        # budget=100, 
        # websiteUrl="", 
        # backgroundCardImage="",
        # galleryImage1="", 
        # galleryImage3="", 
        # galleryImage2="", 
        # description="",
        # fbUrl="tba", 
        # twitterUrl="tba", 
        # youTubeUrl="tba",
        # instagramUrl="tba"),


        # VenueModel(
        # email="",
        # username="", 
        # password="",
        # profileImage = "https://res.cloudinary.com/dgk61wxpy/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1659802002/Findartistsandvenues-profile-images/portrait-of-young-female-bar-owner-picture-id1084751504_dmmlrg.jpg",
        # title="",
        # role="",
        # venueName="",
        # type = venue_type_list,
        # location="",
        # address="", 
        # budget=100, 
        # websiteUrl="", 
        # backgroundCardImage="",
        # galleryImage1="", 
        # galleryImage3="", 
        # galleryImage2="", 
        # description="",
        # fbUrl="tba", 
        # twitterUrl="tba", 
        # youTubeUrl="tba",
        # instagramUrl="tba"),


        # VenueModel(
        # email="",
        # username="", 
        # password="",
        # profileImage = "https://res.cloudinary.com/dgk61wxpy/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1659802002/Findartistsandvenues-profile-images/portrait-of-young-female-bar-owner-picture-id1084751504_dmmlrg.jpg",
        # title="",
        # role="",
        # venueName="",
        # type = venue_type_list,
        # location="",
        # address="", 
        # budget=100, 
        # websiteUrl="", 
        # backgroundCardImage="",
        # galleryImage1="", 
        # galleryImage3="", 
        # galleryImage2="", 
        # description="",
        # fbUrl="tba", 
        # twitterUrl="tba", 
        # youTubeUrl="tba",
        # instagramUrl="tba"),


        # VenueModel(
        # email="",
        # username="", 
        # password="",
        # profileImage = "https://res.cloudinary.com/dgk61wxpy/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1659802002/Findartistsandvenues-profile-images/portrait-of-young-female-bar-owner-picture-id1084751504_dmmlrg.jpg",
        # title="",
        # role="",
        # venueName="",
        # type = venue_type_list,
        # location="",
        # address="", 
        # budget=100, 
        # websiteUrl="", 
        # backgroundCardImage="",
        # galleryImage1="", 
        # galleryImage3="", 
        # galleryImage2="", 
        # description="",
        # fbUrl="tba", 
        # twitterUrl="tba", 
        # youTubeUrl="tba",
        # instagramUrl="tba"),


        # VenueModel(
        # email="",
        # username="", 
        # password="",
        # profileImage = "https://res.cloudinary.com/dgk61wxpy/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1659802002/Findartistsandvenues-profile-images/portrait-of-young-female-bar-owner-picture-id1084751504_dmmlrg.jpg",
        # title="",
        # role="",
        # venueName="",
        # type = venue_type_list,
        # location="",
        # address="", 
        # budget=100, 
        # websiteUrl="", 
        # backgroundCardImage="",
        # galleryImage1="", 
        # galleryImage3="", 
        # galleryImage2="", 
        # description="",
        # fbUrl="tba", 
        # twitterUrl="tba", 
        # youTubeUrl="tba",
        # instagramUrl="tba"),


        # VenueModel(
        # email="",
        # username="", 
        # password="",
        # profileImage = "https://res.cloudinary.com/dgk61wxpy/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1659802002/Findartistsandvenues-profile-images/portrait-of-young-female-bar-owner-picture-id1084751504_dmmlrg.jpg",
        # title="",
        # role="",
        # venueName="",
        # type = venue_type_list,
        # location="",
        # address="", 
        # budget=100, 
        # websiteUrl="", 
        # backgroundCardImage="",
        # galleryImage1="", 
        # galleryImage3="", 
        # galleryImage2="", 
        # description="",
        # fbUrl="tba", 
        # twitterUrl="tba", 
        # youTubeUrl="tba",
        # instagramUrl="tba"),


        # VenueModel(
        # email="",
        # username="", 
        # password="",
        # profileImage = "https://res.cloudinary.com/dgk61wxpy/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1659802002/Findartistsandvenues-profile-images/portrait-of-young-female-bar-owner-picture-id1084751504_dmmlrg.jpg",
        # title="",
        # role="",
        # venueName="",
        # type = venue_type_list,
        # location="",
        # address="", 
        # budget=100, 
        # websiteUrl="", 
        # backgroundCardImage="",
        # galleryImage1="", 
        # galleryImage3="", 
        # galleryImage2="", 
        # description="",
        # fbUrl="tba", 
        # twitterUrl="tba", 
        # youTubeUrl="tba",
        # instagramUrl="tba"),


        # VenueModel(
        # email="",
        # username="", 
        # password="",
        # profileImage = "https://res.cloudinary.com/dgk61wxpy/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1659802002/Findartistsandvenues-profile-images/portrait-of-young-female-bar-owner-picture-id1084751504_dmmlrg.jpg",
        # title="",
        # role="",
        # venueName="",
        # type = venue_type_list,
        # location="",
        # address="", 
        # budget=100, 
        # websiteUrl="", 
        # backgroundCardImage="",
        # galleryImage1="", 
        # galleryImage3="", 
        # galleryImage2="", 
        # description="",
        # fbUrl="tba", 
        # twitterUrl="tba", 
        # youTubeUrl="tba",
        # instagramUrl="tba"),
]

venue_comments_list = [
    VenueCommentModel(content="This is a great Venue", rating=4, venue_id=1, artist_id=1)]


